/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "nwsztnpkjcwxzcmryzml"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im53c3p0bnBramN3eHpjbXJ5em1sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjUyODY0NTQsImV4cCI6MjA4MDg2MjQ1NH0.ZDDZ_KD-bKEnH_8T8WGYgAtMVznCoLpYoAl-yfWLNqE"